name: PR checks

on:
  pull_request:

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@master
      - run: nix flake check --all-systems
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@master
      - run: nix eval --json .#tests
